language: node_js

node_js:
  - 6
  - 4

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

after_script:
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
