language: node_js
node_js:
  - node
  - lts/*
branches:
  only:
    - master
    - /v\d+\.\d+/
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test
after_script:
  - npx codecov
notifications:
  email: false
deploy:
  provider: npm
  email: notcaseywebb@gmail.com
  api_key:
    secure: OKye3iSXUmzijnt7otfKLR2EFjX/cS0XrvLtjKwifvn4whCqEpsZyWD1VIBWFuUddAEntdX8o9akmVTOR64Sjie75oIl12XhHH54c/qNOKFegnaVteRNYnWX8ccDkliu7NOaggPmmRO/ukLgadMcqjkiXbZfVxEan6QvV6wwX1/PEzBEKqgYf9DNf8nrG3988zq0VUeVHPLLLCPOGbTWxoLVwO2MlBKmPGF/KtQWPKSonU/8Mx2gXeraeKmIgd0Q+UTtVAO2+ej3KGQY23d9FmK1UezCNuR8ohH5qiGxAy3y+JH/iuuYwwVBWqVvTgWypxiqM/u13BtJFoYbML9GAiZAlIfb+XzkY0qfkXa2b3cELKJg2FNijlqrHDtU/h16kpdSyq/iRs59YpQPCZLTkml3+nlV4H9M9zKjWJmAGnHaheGFfexvcsqHxvaW8wa+IZv40K91CTiKY2mif1kG1+iwk3tKpwvdezQsmGqLvriVwnYUtQwBzev2Bngajkh641kfUVjvCResfZpODmAFb1qscJ7ANXhQdvSyNDFwSKeiNnplG5uw7wp/69Q/KRvmmOG7+VgmX1Y5BpzBCqa3l2gH7MLph7NzXEBcoEzaJDmGKZljIiSBp1UOBjdeBU5OF7NLoVJC5c4cl9VAX80gQlqqqxadjOiG/frflVDGpks=
  on:
    tags: true
    repo: caseyWebb/taskr-rename
